version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superlongpassword
      MYSQL_USER: api_manager
      MYSQL_PASSWORD: StrongPassword123!
    volumes:
      - ./ini.sql:/docker-entrypoint-initdb.d/ini.sql
      - ./ini2.sql:/docker-entrypoint-initdb.d/ini2.sql
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    environment:
      DB_URL: jdbc:mysql://mysql:3306/event_management_sys?useUnicode=true&characterEncoding=UTF-8
      DB_USERNAME: api_manager
      DB_PASSWORD: StrongPassword123!
      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      PAYOS_CLIENT_ID: ${PAYOS_CLIENT_ID}
      PAYOS_API_KEY: ${PAYOS_API_KEY}
      PAYOS_CHECKSUM_KEY: ${PAYOS_CHECKSUM_KEY}
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend-net
    ports:
      - "5555:5555"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - backend-net
    ports:
      - "3000:3000"  # Expose Next.js on port 3000
    depends_on:
      - mysql
      - backend

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"  # Expose Prometheus on port 9090
    networks:
      - backend-net

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3001:3000"  # Expose Grafana on port 3001
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge